services:
  db:
    image: nouchka/sqlite3:latest
    ports:
      - "8191:8191"
    volumes:
      - ./data/db:/root/db
    environment:
      - SQLITE3_DB=userdata.db
  web:
    build: .
    command: python3.9 server.py 
    ports:
      - "8000:8000"
    depends_on:
      - db