services:
  db:
    image: nouchka/sqlite3:latest
    ports:
      - "8191:8191"
    environment:
      - SQLITE3_DB=userdata1.db
  web:
    build: .
    command: python3 server.py 
    ports:
      - "8000:8000"
    volumes:
      - data:/app
    depends_on:
      - db
volumes:
  data:
